### ISSUE TITLE
I can't enter the dashboard

### ISSUE THREAD

**Issue by yalcincoruh** [nascent-africa/jetstrap#42]
Install Jetstream With Inertia  and 
1.) Uncaught TypeError: Cannot read property 'classList' of undefined
    at dashboard.js:551

2.)Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at app.js:19844
<img width="803" alt="Laravel" src="https://user-images.githubusercontent.com/69513700/117321224-9fd79d00-ae95-11eb-9d0e-d3a74c9562e8.png">

**Comment by yalcincoruh** [comment]
sorry but inpm nstallation error

**Comment by yalcincoruh** [comment]
> Install Jetstream With Inertia and
> 1.) Uncaught TypeError: Cannot read property 'classList' of undefined
> at dashboard.js:551
> 
> 2.)Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
> at app.js:19844
> <img alt="Laravel" width="803" src="https://user-images.githubusercontent.com/69513700/117321224-9fd79d00-ae95-11eb-9d0e-d3a74c9562e8.png">

**Comment by tsommie** [comment]
This is not helpful in any way. please provide details.

**Comment by yalcincoruh** [comment]
I work locally and
php artisan jetstrap: swap inertia
if you continue with the installation without using the --teams switch, and

public function boot ()
     {
         JetstrapFacade :: useAdminLte3 ();
         Paginator :: useBootstrap ();
     }
If you use this method in AppServiceProvider, you encounter this error and a blank page appears in the dashboard.

if
php artisan jetstrap: swap inertia --teams
If you start installing with this command, everything works fine even if it gives the same error

**Comment by yalcincoruh** [comment]
if you don't use this
JetstrapFacade :: useAdminLte3 ();  or JetstrapFacade::useCoreUi3();

everything is OK  .

**Comment by tsommie** [comment]
I will looking into it right away.

**Comment by tsommie** [comment]
Followed the steps as described to try and reproduce this error but got nothing, only a few warnings that were caused by running `jetstream:install inertia --teams` and not using the same `--teams` option when running Jetstrap swap. If your not going to use the `--teams` options then dont run it when installing inertia with jetstream.

Lastly, i dont think this error happens because of the installation process and if you can give more information on how I can reproduce this on my local machine it will be resolved ASAP. For now am closing this issue.
